language: node_js
cache:
  directories:
    - node_modules
    - $HOME/.npm
notifications:
  email: false
node_js: 8
before_script: npx -p greenkeeper-lockfile@1 greenkeeper-lockfile-update
after_script: npx -p greenkeeper-lockfile@1 greenkeeper-lockfile-upload
after_success: npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
